[feat] ticket function
KeywordHanaro/KeywordHanaro_BE pull request #11
Opened 2024-12-17 04:42 UTC by insun-k

번호표 생성 api 입니다 (/ticket)

2024-12-17 05:26 UTC, ninw0205 requested changes
일반 사용 기준으로 다시 수정 부탁드립니다.

2024-12-18 06:19 UTC, mseoa commented on src/main/java/com/hana4/keywordhanaro/controller/ErrorController.java
> +	@ExceptionHandler(KeywordNotFoundException.class)
not found exception 새로 생성하지 않고 NullPointerException 던져서 위에 팀장님이 정의해둔 nullPointerExceptionHandler 재사용해서 타게 해도될 것 같은데 어떠세요? 엔티티마다 not found 던지면 핸들러가 늘어날 것 같아서요!

2024-12-18 06:30 UTC, insun-k commented on src/main/java/com/hana4/keywordhanaro/controller/ErrorController.java
> +	@ExceptionHandler(KeywordNotFoundException.class)
넵! nullPointerExceptionHandler가 좋을 것 같습니다 !

2024-12-18 06:37 UTC, mseoa approved these changes
Ticket 엔티티에 branchId는 나중에 삭제할지 얘기해봐야할 것같네요
고생 많으셨습니다!

2024-12-18 06:38 UTC, merged